Added new yaml file for REA Group Corporation.
scope3data/methodology pull request #54
Opened 2022-10-31 21:24 UTC by pymble2073

This is my first push, to add a new yaml corporation file for REA Group

2022-10-31 21:25 UTC, EmmaLouise2018 commented on data/companies/rea_group/corporate.yaml
> +---
Nice first PR!

2022-11-01 00:49 UTC, bokelley requested changes

2022-11-01 00:49 UTC, bokelley commented on data/companies/rea_group/corporate.yaml
> +  - datacenter_emissions_mt_co2e_per_employee_per_month: 0.0144
This seems like it omitting scope 3 emissions from the software providers and other vendors that they use. I think we should omit.

2022-11-01 00:49 UTC, bokelley commented on data/companies/rea_group/corporate.yaml
> +  - overhead_emissions_mt_co2e_per_employee_per_month: 0.0539
This should be omitted since their methodology isn't comprehensive.

2022-11-15 21:08 UTC, merged